/*
 CDDL HEADER START

 The contents of this file are subject to the terms of the
 Common Development and Distribution License (the "License").
 You may not use this file except in compliance with the License.

 You can obtain a copy of the license at
   https://opensource.org/licenses/CDDL-1.0.
 See the License for the specific language governing permissions
 and limitations under the License.

 When distributing Covered Code, include this CDDL HEADER in each
 file and include the License file at
    https://opensource.org/licenses/CDDL-1.0.
 If applicable, add the following below this CDDL HEADER, with the
 fields enclosed by brackets "[]" replaced with your own identifying
 information: Portions Copyright [yyyy] [name of copyright owner]

 CDDL HEADER END
*/


package self.lesfoster.cylindrical_alignment.viewer.top_component;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import self.lesfoster.cylindrical_alignment.settings.UnifiedSettingsPanel;

/**
 * Platform-managed controls for the main view.
 */
@ConvertAsProperties(
		dtd = "-//self.lesfoster.cylindrical_alignment.viewer.top_component//Controls//EN",
		autostore = false
)
@TopComponent.Description(
		preferredID = ControlsTopComponent.CONTROLS_TOP_COMPONENT_PREFERRED_ID,
		//iconBase="SET/PATH/TO/ICON/HERE", 
		persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "properties", position = 200, openAtStartup = true)
@ActionID(category = "Window", id = "self.lesfoster.cylindrical_alignment.viewer.top_component.ControlsTopComponent")
@ActionReference(path = "Menu/Window", position = 335)
@TopComponent.OpenActionRegistration(
		displayName = "#CTL_ControlsAction",
		preferredID = "ControlsTopComponent"
)
@Messages({
	"CTL_ControlsAction=Controls",
	"CTL_ControlsTopComponent=Settings for Cylinder Widget",
	"HINT_ControlsTopComponent=These controls effect what happens in cyl view."
})
public final class ControlsTopComponent extends TopComponent {
	public static final String CONTROLS_TOP_COMPONENT_PREFERRED_ID = "ControlsTopComponent";

    public ControlsTopComponent() {
        initComponents();
        setName(Bundle.CTL_ControlsTopComponent());
        setToolTipText(Bundle.HINT_ControlsTopComponent());

    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(null);
        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    // End of variables declaration//GEN-END:variables
	@Override
    public void componentOpened() {
        contentPanel.setLayout(new BorderLayout());
        unifiedSettingsPanel = new UnifiedSettingsPanel();
        contentPanel.add(unifiedSettingsPanel, BorderLayout.CENTER);
    }
    public UnifiedSettingsPanel unifiedSettingsPanel;

	@Override
    public void componentClosed() {
        if (unifiedSettingsPanel != null) {
            unifiedSettingsPanel.close();
            contentPanel.remove(unifiedSettingsPanel);
        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
